# Generated by Django 3.2.8 on 2021-10-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlstation',
            name='height',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
