# Generated by Django 3.2.8 on 2021-10-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_controlstation_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlstation',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=22),
        ),
        migrations.AlterField(
            model_name='controlstation',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=22),
        ),
    ]
