# Generated by Django 3.2.8 on 2021-10-20 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('x_northing', models.DecimalField(decimal_places=4, max_digits=22)),
                ('y_easting', models.DecimalField(decimal_places=4, max_digits=22)),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
