# Generated by Django 3.2.8 on 2021-10-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211020_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlstation',
            old_name='user',
            new_name='poster',
        ),
    ]
